import argparse
import sys


#chr_order = ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', \
#             'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', \
#             'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', \
#             'chr22', 'chrX', 'chrY']

def parse_args():
    parser = argparse.ArgumentParser(description='merge HSat1 annotation of the same type and strand within 5 kb')
    parser.add_argument('-i', dest="bedfile", help="bedfile generated by repeatmasker gff file <chrom\\tstart\\tend\\tstrand\\tHSat1_subtype>",required=False)
    parser.add_argument('-o', dest="outbed", help="name of output file [default='out.bed']", default="out.bed",
                        required=False)

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit()

    else:
        return parser.parse_args()


def stat_color():
    satellite_color = {}
    with open("/share/home/zhanglab/user/sunyanqing/human/assembly/satellite.color", 'r') as inf:
        for line in inf:
            tokens = line.strip().split("\t")
            satellite_color[tokens[0]] = tokens[1]
    return satellite_color

def merge(intervals, gaplen):
    """
    :param intervals: List[List[int]]
    :return: List[List[int]]
    """

    intervals.sort(key=lambda x: x[0])
    merged = []
    for interval in intervals:
        # if not merged or merged[-1][-1] < interval[0]:
        # (不连续区间合并)
        if not merged or merged[-1][-1] - interval[0] < -gaplen:
            merged.append(interval)
        else:
            merged[-1][-1] = max(merged[-1][-1], interval[-1])
    return merged


def stat_bed(bedfile, outbed):

    satellite_color = stat_color()

    outf = open(outbed, 'w')
    sat = ""
    chr_interval_lst = {}
    with open(bedfile, 'r') as inf:
        for line in inf:
            tokens = line.strip().split()
            chrom = tokens[0]
            start = int(tokens[1])
            end = int(tokens[2])
            strand = tokens[3]
            sat = tokens[4]
            if (chrom, strand) not in chr_interval_lst:
                chr_interval_lst[(chrom, strand)] = [[start, end]]
            else:
                chr_interval_lst[(chrom, strand)].append([start, end])

    for ichr, strand in chr_interval_lst.keys():
        fintervals = chr_interval_lst.get((ichr, strand), [])
        #rintervals = chr_interval_lst.get((ichr, "-"), [])
        if fintervals != []:
            fmintervals = merge(fintervals, 5000)
            for reg in fmintervals:
                outf.write("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" % (ichr, reg[0], reg[1], sat, 0, strand, reg[0], reg[1], satellite_color[sat]))


        #if rintervals != []:
        #    rmintervals = merge(rintervals, 5000)
        #    for reg in rmintervals:
        #        outf.write("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" % (ichr, reg[0], reg[1], sat, 0, "-", reg[0], reg[1], satellite_color[sat]))

    outf.close()
   
if __name__ == "__main__":
    args = parse_args() 
    stat_bed(args.bedfile, args.outbed) 
        
        
    
            
    
